In [2]:
import pandas as pd

df = pd.read_csv('./data/stock-data.csv')


print(df.head())
print('\n')
print(df.info())

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039


<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB
None

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB

In [9]:
# 문자열을 Timestamp로 번경

df["new_Date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_Date  20 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.2 KB

In [12]:
df['new_Date'] = pd.to_datetime(df['Date']) 

print(df.head())
print(df.info())
print(type(df['new_Date'][0]))

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_Date  20 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.2 KB
None
<class 'pandas.Timestamp'>

In [13]:
pd.DatetimeIndex(["2022-12-25", "2023/01/25"])

DatetimeIndex(['2022-12-25', '2023-01-25'], dtype='datetime64[us]', freq=None)

In [14]:
pd.Timestamp("2023-12-25")

Timestamp('2023-12-25 00:00:00')

In [19]:
# pd.to_datetime("2023년 12월 25일")
# pd.to_datetime("2023:12:25")
print(pd.to_datetime("2022-12-25"))
print(pd.to_datetime("2022/12/25"))
print(pd.to_datetime("2022년 12월 25일", format="%Y년 %m월 %d일"))

2022-12-25 00:00:00
2022-12-25 00:00:00
2022-12-25 00:00:00

In [23]:
# Timestamp를 Period로 변환

dates = [
    "2019-01-01", "2020-03-01", "2021-06-01"
]

ts_dates = pd.to_datetime(dates)
ts_dates

DatetimeIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='datetime64[us]', freq=None)

In [26]:
pr_day = ts_dates.to_period(freq='D')
print(pr_day)
pr_month = ts_dates.to_period(freq='M')
print(pr_month)
pr_year = ts_dates.to_period(freq='Y')
print(pr_year)

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='period[D]')
PeriodIndex(['2019-01', '2020-03', '2021-06'], dtype='period[M]')
PeriodIndex(['2019', '2020', '2021'], dtype='period[Y-DEC]')

In [27]:
# 시계열 데이터 만들기

ts_ms = pd.date_range(
    start="2024-01-01",
    end=None,
    periods=4,
    freq="MS",
    tz="Asia/Seoul"
)

ts_ms

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-02-01 00:00:00+09:00',
               '2024-03-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [31]:
ts_me = pd.date_range(
    "2024-01-01",
    periods=4,
    freq="ME",
    tz="Asia/Seoul"
)

ts_me

DatetimeIndex(['2024-01-31 00:00:00+09:00', '2024-02-29 00:00:00+09:00',
               '2024-03-31 00:00:00+09:00', '2024-04-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [32]:
ts_3m = pd.date_range(
    "2024-01-01",
    periods=6,
    freq="3MS",
    tz="Asia/Seoul"
)

ts_3m

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-07-01 00:00:00+09:00', '2024-10-01 00:00:00+09:00',
               '2025-01-01 00:00:00+09:00', '2025-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3MS')

In [33]:
df = pd.read_csv("./data/stock-data.csv")
df.head()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [34]:
df["new_Date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [37]:
df["Year"] = df["new_Date"].dt.year
df["Month"] = df["new_Date"].dt.year
df["Day"] = df["new_Date"].dt.year

df.head()

,Date,Close,Start,High,Low,Volume,new_Date,Year,Month,Day,Date_Yr,Date_m
0,2018-07-02,10100,10850,10900,10000,137977,2018-07-02,2018,2018,2018,2018,2018-07
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,2018,2018,2018,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,2018,2018,2018,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,2018,2018,2018,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,2018,2018,2018,2018-06

In [36]:
df["Date_Yr"] = df["new_Date"].dt.to_period(freq="Y")
df["Date_m"] = df["new_Date"].dt.to_period(freq="M")
df.head()

,Date,Close,Start,High,Low,Volume,new_Date,Year,Month,Day,Date_Yr,Date_m
0,2018-07-02,10100,10850,10900,10000,137977,2018-07-02,2018,2018,2018,2018,2018-07
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,2018,2018,2018,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,2018,2018,2018,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,2018,2018,2018,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,2018,2018,2018,2018-06

In [41]:
# 날짜데이터 분리

cond = df["Date_m"].astype(str).str.fullmatch("2018-06")
df_june = df[cond]
df_june.head()

,Date,Close,Start,High,Low,Volume,new_Date,Year,Month,Day,Date_Yr,Date_m
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,2018,2018,2018,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,2018,2018,2018,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,2018,2018,2018,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,2018,2018,2018,2018-06
5,2018-06-25,11150,11400,11450,11000,55519,2018-06-25,2018,2018,2018,2018,2018-06

In [ ]:
# 날짜데이터 분리2

df["Date_m"] == pd.Period("2018-06")

In [42]:
df_june2 = df[df['Date_m'] == pd.Period('2018-06')]
df_june2.head()

,Date,Close,Start,High,Low,Volume,new_Date,Year,Month,Day,Date_Yr,Date_m
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,2018,2018,2018,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,2018,2018,2018,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,2018,2018,2018,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,2018,2018,2018,2018-06
5,2018-06-25,11150,11400,11450,11000,55519,2018-06-25,2018,2018,2018,2018,2018-06

In [43]:
df_june = df_june.set_index('new_Date')
df_june.head()

,Date,Close,Start,High,Low,Volume,Year,Month,Day,Date_Yr,Date_m
new_Date,,,,,,,,,,,
2018-06-29,2018-06-29,10700,10550,10900,9990,170253,2018,2018,2018,2018,2018-06
2018-06-28,2018-06-28,10400,10900,10950,10150,155769,2018,2018,2018,2018,2018-06
2018-06-27,2018-06-27,10900,10800,11050,10500,133548,2018,2018,2018,2018,2018-06
2018-06-26,2018-06-26,10800,10900,11000,10700,63039,2018,2018,2018,2018,2018-06
2018-06-25,2018-06-25,11150,11400,11450,11000,55519,2018,2018,2018,2018,2018-06

In [44]:
df = pd.read_csv('./data/stock-data.csv')

df['new_Date'] = pd.to_datetime(df['Date']) 

df = df.set_index('new_Date').sort_index()

print(df.head())
print(df.index)

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258
DatetimeIndex(['2018-06-01', '2018-06-04', '2018-06-05', '2018-06-07',
               '2018-06-08', '2018-06-11', '2018-06-12', '2018-06-14',
               '2018-06-15', '2018-06-18', '2018-06-19', '2018-06-20',
               '2018-06-21', '2018-06-22', '2018-06-25', '2018-06-26',
               '2018-06-27', '2018-06-28', '2018-06-29', '2018-07-02'],
              dtype='datetime64[us]', name='new_Date', freq=None)

In [45]:
df.loc['2018-06-27']

Date      2018-06-27
Close          10900
Start          10800
High           11050
Low            10500
Volume        133548
Name: 2018-06-27 00:00:00, dtype: object

In [46]:
df.loc['2018-07']

                  Date  Close  Start   High    Low  Volume
new_Date
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [47]:
df.loc['2018-06-27':'2018-07-02']

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [48]:
df[df.index < '2018-06-05']

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171

In [49]:
# 시간 인덱스 활용

df.loc[pd.Timestamp(2018, 6, 27):pd.Timestamp(2018, 7, 2)]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [50]:
df.loc[pd.Timestamp(2018, 6, 27, 10, 30, 0):pd.Timestamp(2018, 7, 2, 23, 59, 59)]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [67]:
print(pd.Timedelta("1 days"))
print(pd.Timedelta(days=1))
print(pd.Timedelta("1 days 1 hours 1 minutes, 1 seconds"))
print(pd.Timedelta(days=1, hours=1, minutes=1, seconds=1))

1 days 00:00:00
1 days 00:00:00
1 days 01:01:01
1 days 01:01:01

In [68]:
pd.to_timedelta(["1 days", "3 hours"])

TimedeltaIndex(['1 days 00:00:00', '0 days 03:00:00'], dtype='timedelta64[us]', freq=None)

In [ ]:
pd.to_timedelta(["1 days", "1 hours"])

TimedeltaIndex(['1 days 00:00:00', '0 days 01:00:00'], dtype='timedelta64[us]', freq=None)

In [69]:
a = df.index
print(a)

DatetimeIndex(['2018-06-01', '2018-06-04', '2018-06-05', '2018-06-07',
               '2018-06-08', '2018-06-11', '2018-06-12', '2018-06-14',
               '2018-06-15', '2018-06-18', '2018-06-19', '2018-06-20',
               '2018-06-21', '2018-06-22', '2018-06-25', '2018-06-26',
               '2018-06-27', '2018-06-28', '2018-06-29', '2018-07-02'],
              dtype='datetime64[us]', name='new_Date', freq=None)

In [70]:
b = pd.Timestamp('2018-07-03') - a
print(b)

TimedeltaIndex(['32 days', '29 days', '28 days', '26 days', '25 days',
                '22 days', '21 days', '19 days', '18 days', '15 days',
                '14 days', '13 days', '12 days', '11 days',  '8 days',
                 '7 days',  '6 days',  '5 days',  '4 days',  '1 days'],
               dtype='timedelta64[us]', name='new_Date', freq=None)

In [73]:
c = a + pd.Timedelta(days=1)
print(c)

print(c.min())
print(c.max())

DatetimeIndex(['2018-06-02', '2018-06-05', '2018-06-06', '2018-06-08',
               '2018-06-09', '2018-06-12', '2018-06-13', '2018-06-15',
               '2018-06-16', '2018-06-19', '2018-06-20', '2018-06-21',
               '2018-06-22', '2018-06-23', '2018-06-26', '2018-06-27',
               '2018-06-28', '2018-06-29', '2018-06-30', '2018-07-03'],
              dtype='datetime64[us]', name='new_Date', freq=None)
2018-06-02 00:00:00
2018-07-03 00:00:00

In [74]:
# 시계열 변환

df = pd.read_csv("./data/stock-data.csv")

In [75]:
df['new_Date'] = pd.to_datetime(df['Date'])  
df = df.drop(columns=['Date'])
df.head()

   Close  Start   High    Low  Volume   new_Date
0  10100  10850  10900  10000  137977 2018-07-02
1  10700  10550  10900   9990  170253 2018-06-29
2  10400  10900  10950  10150  155769 2018-06-28
3  10900  10800  11050  10500  133548 2018-06-27
4  10800  10900  11000  10700   63039 2018-06-26

In [76]:
df = df.set_index("new_Date").sort_index()
ts = df.head(10)

In [78]:
ts.shift(1)

              Close    Start     High      Low    Volume
new_Date
2018-06-01      NaN      NaN      NaN      NaN       NaN
2018-06-04  11900.0  11800.0  12100.0  11750.0   32062.0
2018-06-05  11900.0  11900.0  12200.0  11700.0   25171.0
2018-06-07  12150.0  11800.0  12250.0  11800.0   42485.0
2018-06-08  11950.0  12200.0  12300.0  11900.0   49088.0
2018-06-11  11950.0  11950.0  12200.0  11800.0   59258.0
2018-06-12  11950.0  12000.0  12250.0  11950.0   62293.0
2018-06-14  13200.0  12200.0  13300.0  12050.0  558148.0
2018-06-15  13450.0  13200.0  13700.0  13150.0  347451.0
2018-06-18  13400.0  13600.0  13600.0  12900.0  201376.0

In [79]:
ts.shift(-2)

              Close    Start     High      Low    Volume
new_Date
2018-06-01  12150.0  11800.0  12250.0  11800.0   42485.0
2018-06-04  11950.0  12200.0  12300.0  11900.0   49088.0
2018-06-05  11950.0  11950.0  12200.0  11800.0   59258.0
2018-06-07  11950.0  12000.0  12250.0  11950.0   62293.0
2018-06-08  13200.0  12200.0  13300.0  12050.0  558148.0
2018-06-11  13450.0  13200.0  13700.0  13150.0  347451.0
2018-06-12  13400.0  13600.0  13600.0  12900.0  201376.0
2018-06-14  12000.0  13400.0  13400.0  12000.0  309787.0
2018-06-15      NaN      NaN      NaN      NaN       NaN
2018-06-18      NaN      NaN      NaN      NaN       NaN

In [80]:
ts.shift(3, freq="D")

            Close  Start   High    Low  Volume
new_Date
2018-06-04  11900  11800  12100  11750   32062
2018-06-07  11900  11900  12200  11700   25171
2018-06-08  12150  11800  12250  11800   42485
2018-06-10  11950  12200  12300  11900   49088
2018-06-11  11950  11950  12200  11800   59258
2018-06-14  11950  12000  12250  11950   62293
2018-06-15  13200  12200  13300  12050  558148
2018-06-17  13450  13200  13700  13150  347451
2018-06-18  13400  13600  13600  12900  201376
2018-06-21  12000  13400  13400  12000  309787

In [81]:
ts.asfreq('5D')

              Close    Start     High      Low   Volume
new_Date
2018-06-01  11900.0  11800.0  12100.0  11750.0  32062.0
2018-06-06      NaN      NaN      NaN      NaN      NaN
2018-06-11  11950.0  12000.0  12250.0  11950.0  62293.0
2018-06-16      NaN      NaN      NaN      NaN      NaN

In [82]:
ts.asfreq('5D', method='bfill')

            Close  Start   High    Low  Volume
new_Date
2018-06-01  11900  11800  12100  11750   32062
2018-06-06  11950  12200  12300  11900   49088
2018-06-11  11950  12000  12250  11950   62293
2018-06-16  12000  13400  13400  12000  309787

In [83]:
print(ts.resample("3B"))

ts.resample("3B").sum()

DatetimeIndexResampler [freq=<3 * BusinessDays>, closed=left, label=left, convention=start, origin=start_day]

            Close  Start   High    Low  Volume
new_Date
2018-06-01  35950  35500  36550  35250   99718
2018-06-06  23900  24150  24500  23700  108346
2018-06-11  25150  24200  25550  24000  620441
2018-06-14  38850  40200  40700  38050  858614

In [84]:
ts.rolling(window=3).sum()

              Close    Start     High      Low     Volume
new_Date
2018-06-01      NaN      NaN      NaN      NaN        NaN
2018-06-04      NaN      NaN      NaN      NaN        NaN
2018-06-05  35950.0  35500.0  36550.0  35250.0    99718.0
2018-06-07  36000.0  35900.0  36750.0  35400.0   116744.0
2018-06-08  36050.0  35950.0  36750.0  35500.0   150831.0
2018-06-11  35850.0  36150.0  36750.0  35650.0   170639.0
2018-06-12  37100.0  36150.0  37750.0  35800.0   679699.0
2018-06-14  38600.0  37400.0  39250.0  37150.0   967892.0
2018-06-15  40050.0  39000.0  40600.0  38100.0  1106975.0
2018-06-18  38850.0  40200.0  40700.0  38050.0   858614.0

In [85]:
ts.rolling(window='3D').sum()

              Close    Start     High      Low    Volume
new_Date
2018-06-01  11900.0  11800.0  12100.0  11750.0   32062.0
2018-06-04  11900.0  11900.0  12200.0  11700.0   25171.0
2018-06-05  24050.0  23700.0  24450.0  23500.0   67656.0
2018-06-07  24100.0  24000.0  24550.0  23700.0   91573.0
2018-06-08  23900.0  24150.0  24500.0  23700.0  108346.0
2018-06-11  11950.0  12000.0  12250.0  11950.0   62293.0
2018-06-12  25150.0  24200.0  25550.0  24000.0  620441.0
2018-06-14  26650.0  25400.0  27000.0  25200.0  905599.0
2018-06-15  26850.0  26800.0  27300.0  26050.0  548827.0
2018-06-18  12000.0  13400.0  13400.0  12000.0  309787.0