In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("./data/auto-mpg.csv", header=None)
print(df)

df.columns = [
    "mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model year", "origin", "name"
]

print(df)

        0  1      2      3       4     5   6  7                          8
0    18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1    15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2    18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3    16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4    17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino
..    ... ..    ...    ...     ...   ...  .. ..                        ...
393  27.0  4  140.0  86.00  2790.0  15.6  82  1            ford mustang gl
394  44.0  4   97.0  52.00  2130.0  24.6  82  2                  vw pickup
395  32.0  4  135.0  84.00  2295.0  11.6  82  1              dodge rampage
396  28.0  4  120.0  79.00  2625.0  18.6  82  1                ford ranger
397  31.0  4  119.0  82.00  2720.0  19.4  82  1                 chevy s-10

[398 rows x 9 columns]
      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0      130.0  3504.0          12.0
1    15.0          8         350.0      165.0  3693.0          11.5
2    18.0          8         318.0      150.0  3436.0          11.0
3    16.0          8         304.0      150.0  3433.0          12.0
4    17.0          8         302.0      140.0  3449.0          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0      86.00  2790.0          15.6
394  44.0          4          97.0      52.00  2130.0          24.6
395  32.0          4         135.0      84.00  2295.0          11.6
396  28.0          4         120.0      79.00  2625.0          18.6
397  31.0          4         119.0      82.00  2720.0          19.4

     model year  origin                       name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]

In [8]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [9]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [10]:
df.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320

In [11]:
df.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
5,15.0,8,429.0,198.0,4341.0,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220.0,4354.0,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215.0,4312.0,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225.0,4425.0,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190.0,3850.0,8.5,70,1,amc ambassador dpl

In [13]:
# 데이터 요약 정보 확인하기
## 데이터프레임의 크기 (행, 열)
## DataFrame객체.shape

print(df.shape)

(398, 9)

In [14]:
# 데이터프레임의 기본 정보
## DataFrame객체.info()

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB
None

In [15]:
# 자료형 알아보기

print(df.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horsepower          str
weight          float64
acceleration    float64
model year        int64
origin            int64
name                str
dtype: object

In [17]:
# 특정 필드의 데이터 타입 확인

print(df["mpg"].dtype)

float64

In [18]:
# 데이터프레임의 기술 통계 정보 요약

## DataFrame객체.describe()

print(df.describe())

              mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000
mean    23.514573    5.454774    193.425879  2970.424623     15.568090
std      7.815984    1.701004    104.269838   846.841774      2.757689
min      9.000000    3.000000     68.000000  1613.000000      8.000000
25%     17.500000    4.000000    104.250000  2223.750000     13.825000
50%     23.000000    4.000000    148.500000  2803.500000     15.500000
75%     29.000000    8.000000    262.000000  3608.000000     17.175000
max     46.600000    8.000000    455.000000  5140.000000     24.800000

       model year      origin
count  398.000000  398.000000
mean    76.010050    1.572864
std      3.697627    0.802055
min     70.000000    1.000000
25%     73.000000    1.000000
50%     76.000000    1.000000
75%     79.000000    2.000000
max     82.000000    3.000000

In [19]:
print(df.describe(include="all"))

               mpg   cylinders  displacement horsepower       weight  \
count   398.000000  398.000000    398.000000        398   398.000000
unique         NaN         NaN           NaN         94          NaN
top            NaN         NaN           NaN      150.0          NaN
freq           NaN         NaN           NaN         22          NaN
mean     23.514573    5.454774    193.425879        NaN  2970.424623
std       7.815984    1.701004    104.269838        NaN   846.841774
min       9.000000    3.000000     68.000000        NaN  1613.000000
25%      17.500000    4.000000    104.250000        NaN  2223.750000
50%      23.000000    4.000000    148.500000        NaN  2803.500000
75%      29.000000    8.000000    262.000000        NaN  3608.000000
max      46.600000    8.000000    455.000000        NaN  5140.000000

        acceleration  model year      origin        name
count     398.000000  398.000000  398.000000         398
unique           NaN         NaN         NaN         305
top              NaN         NaN         NaN  ford pinto
freq             NaN         NaN         NaN           6
mean       15.568090   76.010050    1.572864         NaN
std         2.757689    3.697627    0.802055         NaN
min         8.000000   70.000000    1.000000         NaN
25%        13.825000   73.000000    1.000000         NaN
50%        15.500000   76.000000    1.000000         NaN
75%        17.175000   79.000000    2.000000         NaN
max        24.800000   82.000000    3.000000         NaN

In [20]:
print(df.describe(include="number"))

              mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000
mean    23.514573    5.454774    193.425879  2970.424623     15.568090
std      7.815984    1.701004    104.269838   846.841774      2.757689
min      9.000000    3.000000     68.000000  1613.000000      8.000000
25%     17.500000    4.000000    104.250000  2223.750000     13.825000
50%     23.000000    4.000000    148.500000  2803.500000     15.500000
75%     29.000000    8.000000    262.000000  3608.000000     17.175000
max     46.600000    8.000000    455.000000  5140.000000     24.800000

       model year      origin
count  398.000000  398.000000
mean    76.010050    1.572864
std      3.697627    0.802055
min     70.000000    1.000000
25%     73.000000    1.000000
50%     76.000000    1.000000
75%     79.000000    2.000000
max     82.000000    3.000000

In [21]:
print(df.describe(include="object"))

       horsepower        name
count         398         398
unique         94         305
top         150.0  ford pinto
freq           22           6

C:\Users\KDS-22\AppData\Local\Temp\ipykernel_21656\1129007761.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include="object"))

In [22]:
print(df.describe(exclude="object"))

              mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000
mean    23.514573    5.454774    193.425879  2970.424623     15.568090
std      7.815984    1.701004    104.269838   846.841774      2.757689
min      9.000000    3.000000     68.000000  1613.000000      8.000000
25%     17.500000    4.000000    104.250000  2223.750000     13.825000
50%     23.000000    4.000000    148.500000  2803.500000     15.500000
75%     29.000000    8.000000    262.000000  3608.000000     17.175000
max     46.600000    8.000000    455.000000  5140.000000     24.800000

       model year      origin
count  398.000000  398.000000
mean    76.010050    1.572864
std      3.697627    0.802055
min     70.000000    1.000000
25%     73.000000    1.000000
50%     76.000000    1.000000
75%     79.000000    2.000000
max     82.000000    3.000000

In [23]:
# 데이터 개수 확인

df = pd.read_csv("./data/auto-mpg.csv", header=None)
print(df)

df.columns = [
    "mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model year", "origin", "name"
]

print(df)

        0  1      2      3       4     5   6  7                          8
0    18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1    15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2    18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3    16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4    17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino
..    ... ..    ...    ...     ...   ...  .. ..                        ...
393  27.0  4  140.0  86.00  2790.0  15.6  82  1            ford mustang gl
394  44.0  4   97.0  52.00  2130.0  24.6  82  2                  vw pickup
395  32.0  4  135.0  84.00  2295.0  11.6  82  1              dodge rampage
396  28.0  4  120.0  79.00  2625.0  18.6  82  1                ford ranger
397  31.0  4  119.0  82.00  2720.0  19.4  82  1                 chevy s-10

[398 rows x 9 columns]
      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0      130.0  3504.0          12.0
1    15.0          8         350.0      165.0  3693.0          11.5
2    18.0          8         318.0      150.0  3436.0          11.0
3    16.0          8         304.0      150.0  3433.0          12.0
4    17.0          8         302.0      140.0  3449.0          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0      86.00  2790.0          15.6
394  44.0          4          97.0      52.00  2130.0          24.6
395  32.0          4         135.0      84.00  2295.0          11.6
396  28.0          4         120.0      79.00  2625.0          18.6
397  31.0          4         119.0      82.00  2720.0          19.4

     model year  origin                       name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]

In [26]:
print(df.count())

mpg             398
cylinders       398
displacement    398
horsepower      398
weight          398
acceleration    398
model year      398
origin          398
name            398
dtype: int64

In [27]:
print(type(df.count()))

<class 'pandas.Series'>

In [38]:
# 각 열의 고유값 개수

# DataFrame객체["열이름"].value_counts()

unique_value = df["origin"].value_counts()
print(unique_value)

unique_value = df["origin"].value_counts().iloc[1]
print(unique_value)

origin
1    249
3     79
2     70
Name: count, dtype: int64
79

In [40]:
unique_values_ratio = df["origin"].value_counts(True)
print(unique_values_ratio)

origin
1    0.625628
3    0.198492
2    0.175879
Name: proportion, dtype: float64

In [43]:
(df["origin"].value_counts(True) * 100).round(1)

origin
1    62.6
3    19.8
2    17.6
Name: proportion, dtype: float64