In [10]:
# 데이터프레임의 불린 인덱싱 : DataFrame객체[불린 시리즈]

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
df = titanic.loc[:9,["age", "fare"]]

print(df)

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [11]:
df["age"] < 10

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
Name: age, dtype: bool

In [12]:
print(df[df["age"] < 10])

   age    fare
7  2.0  21.075

In [7]:
df["age"] < 20

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool

In [13]:
print(df.loc[df["age"] < 20])

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [14]:
print(df[df["age"] < 20])

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [15]:
print(~(df["age"] < 20))

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7    False
8     True
9    False
Name: age, dtype: bool

In [16]:
print(df.loc[~(df["age"] < 20)])

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [24]:
(titanic.age >= 10) & (titanic.age < 20)

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool

In [26]:
titanic[(titanic.age >= 10) & (titanic.age < 20)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,1,1,female,16.0,0,1,39.4000,S,First,woman,False,D,Southampton,yes,False
855,1,3,female,18.0,0,1,9.3500,S,Third,woman,False,NaN,Southampton,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [27]:
mask1 = (titanic.age >= 10) & (titanic.age < 20)
titanic[mask1]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,1,1,female,16.0,0,1,39.4000,S,First,woman,False,D,Southampton,yes,False
855,1,3,female,18.0,0,1,9.3500,S,Third,woman,False,NaN,Southampton,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [29]:
# titanic["age"]
mask2 = (titanic.age < 10) & (titanic.sex == "female")
print(titanic.loc[mask2].head())

     survived  pclass     sex  age  sibsp  parch     fare embarked   class  \
10          1       3  female  4.0      1      1  16.7000        S   Third
24          0       3  female  8.0      3      1  21.0750        S   Third
43          1       2  female  3.0      1      2  41.5792        C  Second
58          1       2  female  5.0      1      2  27.7500        S  Second
119         0       3  female  2.0      4      2  31.2750        S   Third

       who  adult_male deck  embark_town alive  alone
10   child       False    G  Southampton   yes  False
24   child       False  NaN  Southampton    no  False
43   child       False  NaN    Cherbourg   yes  False
58   child       False  NaN  Southampton   yes  False
119  child       False  NaN  Southampton    no  False

In [31]:
mask3 = (titanic["age"] < 10) | (titanic["age"] >= 60)
print(titanic[mask3])

     survived  pclass     sex    age  sibsp  parch     fare embarked   class  \
7           0       3    male   2.00      3      1  21.0750        S   Third
10          1       3  female   4.00      1      1  16.7000        S   Third
16          0       3    male   2.00      4      1  29.1250        Q   Third
24          0       3  female   8.00      3      1  21.0750        S   Third
33          0       2    male  66.00      0      0  10.5000        S  Second
..        ...     ...     ...    ...    ...    ...      ...      ...     ...
831         1       2    male   0.83      1      1  18.7500        S  Second
850         0       3    male   4.00      4      2  31.2750        S   Third
851         0       3    male  74.00      0      0   7.7750        S   Third
852         0       3  female   9.00      1      1  15.2458        C   Third
869         1       3    male   4.00      1      1  11.1333        S   Third

       who  adult_male deck  embark_town alive  alone
7    child       False  NaN  Southampton    no  False
10   child       False    G  Southampton   yes  False
16   child       False  NaN   Queenstown    no  False
24   child       False  NaN  Southampton    no  False
33     man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
831  child       False  NaN  Southampton   yes  False
850  child       False  NaN  Southampton    no  False
851    man        True  NaN  Southampton    no   True
852  child       False  NaN    Cherbourg    no  False
869  child       False  NaN  Southampton   yes  False

[88 rows x 15 columns]

In [32]:
# query() 매서드를 활용한 필터링 : DataFrame객체.query(조건 문자열)

print(df.query("age < 20"))

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [33]:
df.query("age >= 20 or fare < 15")

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [40]:
# isin() 매서드 활용
# isin() 매서드를 활용한 필터링 : DataFrame객체.isin(추출값의 리스트)

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")

pd.set_option("display.max_columns", 10)

mask1 = titanic["embark_town"] == "Southampton"
mask2 = titanic["embark_town"] == "Queenstown"

df_boolean = titanic[mask1 | mask2]
print(df_boolean.head())

   survived  pclass     sex   age  sibsp  ...  adult_male  deck  embark_town  \
0         0       3    male  22.0      1  ...        True   NaN  Southampton
2         1       3  female  26.0      0  ...       False   NaN  Southampton
3         1       1  female  35.0      1  ...       False     C  Southampton
4         0       3    male  35.0      0  ...        True   NaN  Southampton
5         0       3    male   NaN      0  ...        True   NaN   Queenstown

  alive  alone
0    no  False
2   yes   True
3   yes  False
4    no   True
5    no   True

[5 rows x 15 columns]

In [43]:
mask3 = titanic["embark_town"].isin(["Southampton", "Queenstown"])
titanic[mask3]

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,...,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,...,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,...,False,B,Southampton,yes,True
888,0,3,female,NaN,1,...,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,...,True,NaN,Queenstown,no,True