

다음의 데이터는 153일 동안 측정한 공기 질에 대한 데이터이다.

**데이터 URL**
```
https://raw.githubusercontent.com/YoungjinBD/dataset/main/airquality.csv
```

| 컬럼 | 설명 |
|---|---|
| Ozone | 오존 농도 |
| Solar.R | 태양 복사 강도 |
| Wind | 평균 풍속 |
| Temp | 최대 온도 |
| Month | 월 |
| Day | 일 |

In [36]:
import pandas as pd

In [37]:
import pandas as pd
import numpy as np

# 데이터 로드
data_url = "https://raw.githubusercontent.com/YoungjinBD/dataset/main/airquality.csv"
airquality = pd.read_csv(data_url)
airquality.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2
2   12.0    149.0  12.6    74      5    3
3   18.0    313.0  11.5    62      5    4
4    NaN      NaN  14.3    56      5    5

## 문제 ① 결측치 처리 및 평균 비교

`airquality` 데이터에 대해서 **결측치가 가장 많은 변수**를 찾아서 해당 결측치를 **0으로 대치**하고,  
**결측치를 제외한 평균**과 **0으로 대치한 후의 평균**과의 차이를 구하시오.

> 출력: 두 평균의 차이 (절대값 여부는 풀이 방식에 따름)

In [38]:
airquality

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
4      NaN      NaN  14.3    56      5    5
..     ...      ...   ...   ...    ...  ...
148   30.0    193.0   6.9    70      9   26
149    NaN    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[153 rows x 6 columns]

In [39]:
airquality.isnull().sum()

Ozone      37
Solar.R     7
Wind        0
Temp        0
Month       0
Day         0
dtype: int64

In [40]:
avg1 = airquality["Ozone"].mean()
print(avg1)

42.12931034482759

In [41]:
airquality["Ozone"] = airquality["Ozone"].fillna(0)
avg2 = airquality["Ozone"].mean()
print(avg2)

31.941176470588236

In [47]:
result1 = avg1 - avg2
result1 = round(result1, 3)
print(result1)

10.188

In [43]:
airquality

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
4      0.0      NaN  14.3    56      5    5
..     ...      ...   ...   ...    ...  ...
148   30.0    193.0   6.9    70      9   26
149    0.0    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[153 rows x 6 columns]

## 문제 ② Min-Max / Z 정규화 평균 비교

`Wind` 변수에 대해서 **Min-Max 정규화**를 수행한 후 평균값과  
**Z 정규화(표준화)**를 수행한 후 평균값의 차이를 구하시오.

- Min-Max 정규화: $(x - min) / (max - min)$
- Z 정규화: $(x - mean) / std$

> 출력: 두 평균의 차이

In [54]:
# 정답
airquality["Wind"].head()
wind_min = airquality["Wind"].min()
wind_max = airquality["Wind"].max()
wind_mean = airquality["Wind"].mean()
wind_std = airquality["Wind"].std()

airquality["minmax"] = (airquality["Wind"] - wind_min) / wind_max - wind_min

airquality["zscor"] = (airquality["Wind"] - wind_mean) / wind_std

result2 = airquality["minmax"].mean() - airquality["zscor"].mean()
result2 = round(result2, 2)
print(result2)

-1.3

In [55]:

def mm(a):
    return (a-airquality["Wind"].min())/(airquality["Wind"].max() - airquality["Wind"].min())
    

res = airquality["Wind"].apply(mm).mean()
# print(res)

def z(b):
    return (b-airquality["Wind"].mean()) / airquality["Wind"].std()

res2 = airquality["Wind"].apply(z).mean()
# print(res2)

result2 = res - res2
print(round(result2, 2))

0.43

## 문제 ③ 월별 평균 기온

월별(5월~9월) **평균 기온(`Temp`)**을 구하시오.

> 출력: Month별 Temp 평균

In [45]:
airquality

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
4      0.0      NaN  14.3    56      5    5
..     ...      ...   ...   ...    ...  ...
148   30.0    193.0   6.9    70      9   26
149    0.0    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[153 rows x 6 columns]

In [46]:
result3 = airquality.groupby("Month")["Temp"].mean()
result3

Month
5    65.548387
6    79.100000
7    83.903226
8    83.967742
9    76.900000
Name: Temp, dtype: float64

In [ ]:
grouped = airquality.groupby("Month")