# 01 제1유형

기출문제 6회 제1유형 연습입니다.  
각 문제는 **서로 다른 CSV**를 사용합니다.

**데이터 URL (공통 경로)**
```
https://raw.githubusercontent.com/YoungjinBD/dataset/main/
```

In [66]:
import pandas as pd
import numpy as np

In [67]:
df = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/data_6_1_1.csv")
df.head()

    구급대                 출동시간                 도착시간
0  구급대8  2020-07-10 06:11:45  2020-07-10 06:52:06
1  구급대9  2020-07-13 06:12:21  2020-07-13 07:58:59
2  구급대1  2020-07-06 06:12:29  2020-07-06 07:51:55
3  구급대5  2020-07-21 06:11:41  2020-07-21 08:08:36
4  구급대1  2020-07-29 06:12:00  2020-07-29 07:24:21

## 문제 ① 구급대 평균 이동시간

주어진 데이터를 이용하여 **이동시간**(출동시간과 도착시간의 차이)이  
평균적으로 **가장 오래 걸린 구급대**의 이동시간을 구하시오.

- 분 단위로 환산
- 반올림하여 **정수**로 출력

**데이터**: `data_6_1_1.csv`
```
https://raw.githubusercontent.com/YoungjinBD/dataset/main/data_6_1_1.csv
```

> 출력: 평균 이동시간(분, 정수)

In [68]:
df["출동시간"] = pd.to_datetime(df["출동시간"])
df["도착시간"] = pd.to_datetime(df["도착시간"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   구급대     100 non-null    str
 1   출동시간    100 non-null    datetime64[us]
 2   도착시간    100 non-null    datetime64[us]
dtypes: datetime64[us](2), str(1)
memory usage: 2.5 KB

In [69]:
df["출동시간_분"] = df["출동시간"].dt.minute
df["도착시간_분"] = df["도착시간"].dt.minute
df.head()

    구급대                출동시간                도착시간  출동시간_분  도착시간_분
0  구급대8 2020-07-10 06:11:45 2020-07-10 06:52:06      11      52
1  구급대9 2020-07-13 06:12:21 2020-07-13 07:58:59      12      58
2  구급대1 2020-07-06 06:12:29 2020-07-06 07:51:55      12      51
3  구급대5 2020-07-21 06:11:41 2020-07-21 08:08:36      11       8
4  구급대1 2020-07-29 06:12:00 2020-07-29 07:24:21      12      24

In [70]:
df["차이"] = df["도착시간_분"] - df["출동시간_분"]
result1 = df.groupby("구급대")["차이"].mean().max()
print(round(result1, 2))

23.33

In [71]:
df2 = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/data_6_1_2.csv")
df2.head()

   대학교명  교수  경영학과  경제학과  컴퓨터공학과  산업공학과  국문학과  영문학과
0  대학교1  20   121    72     158    131    77    59
1  대학교2  31   178   139     145    137    63    90
2  대학교3  23   136   139     154    111    91    50
3  대학교4  32    72   136      67     51   133   159
4  대학교5  22    61    73      86     82    55   124

## 문제 ② 교수 1인당 학생 수가 가장 많은 대학

주어진 데이터를 이용하여 **교수 1인당 맡고 있는 학생 수**가 가장 많은 대학교를 찾고,  
그 대학교의 **전체 교수 수**를 구하시오. (**정수**로 출력)

**데이터**: `data_6_1_2.csv`
```
https://raw.githubusercontent.com/YoungjinBD/dataset/main/data_6_1_2.csv
```

> 출력: 해당 대학교의 전체 교수 수(정수)

In [72]:
sum_stu = df2.loc[:, "경영학과" : "영문학과"].sum(axis=1)
sum_stu.head()

0    618
1    752
2    681
3    618
4    481
dtype: int64

In [73]:
df2["교수1인당학생수"] = sum_stu / df2["교수"]
df2.head()

   대학교명  교수  경영학과  경제학과  컴퓨터공학과  산업공학과  국문학과  영문학과   교수1인당학생수
0  대학교1  20   121    72     158    131    77    59  30.900000
1  대학교2  31   178   139     145    137    63    90  24.258065
2  대학교3  23   136   139     154    111    91    50  29.608696
3  대학교4  32    72   136      67     51   133   159  19.312500
4  대학교5  22    61    73      86     82    55   124  21.863636

In [74]:
df2 = df2.sort_values("교수1인당학생수", ascending=False)
df2.head()

     대학교명  교수  경영학과  경제학과  컴퓨터공학과  산업공학과  국문학과  영문학과   교수1인당학생수
45  대학교46  22   163   189     192    121    99   183  43.045455
48  대학교49  21   150   158     159     78    65   195  38.333333
7    대학교8  19   141    81     101    118   151   123  37.631579
25  대학교26  19    89   127     135    112   124   121  37.263158
43  대학교44  22    87   106     167    160   101   153  35.181818

In [75]:
22

22

In [109]:
df3 = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/data_6_1_3.csv")
df3.head()

          날짜  폭력범죄  지능범죄  교통범죄  절도범죄  경제범죄  정치범죄 주요검찰청명
0  2018년 01월    28   127    90    73    33   202   검찰청1
1  2018년 02월    16   137    72    80    30   180   검찰청5
2  2018년 03월    29   140    70    79    34   211   검찰청5
3  2018년 04월    10   140    90    65    31   184   검찰청1
4  2018년 05월    11   138    70    75    35   190   검찰청1

## 문제 ③ 연도별 총 범죄 건수 월평균

주어진 데이터를 이용하여 **연도별 총 범죄 건수의 월평균** 값을 구하고,  
그 값이 **가장 큰 연도**의 총 범죄 건수 월평균 값을 집계하시오.

- 반올림하여 **정수**로 출력

**데이터**: `data_6_1_3.csv`
```
https://raw.githubusercontent.com/YoungjinBD/dataset/main/data_6_1_3.csv
```

> 출력: 월평균 최댓값(정수)

In [108]:
df3["총범죄수"] = df3.loc[:, "폭력범죄" : "정치범죄"].sum(axis=1)

# df3.head()
df3["날짜"] = df3["날짜"].str.replace("년", "-")
df3["날짜"] = df3["날짜"].str.replace(["월", " "], "")
df3.head()
df3["날짜"] = pd.to_datetime(df3["날짜"])
# df3.info()

AttributeError: Can only use .str accessor with string values, not datetime64