# 01 제1유형

기출문제 5회 제1유형 연습입니다.  
각 문제는 **서로 다른 CSV**를 사용합니다.

**데이터 URL (공통 경로)**
```
https://raw.githubusercontent.com/YoungjinBD/dataset/main/
```

> 한글 CSV는 `encoding="cp949"`가 필요할 수 있습니다.

In [2]:
import pandas as pd
import numpy as np

## 문제 ① 음식물쓰레기 2L 종량제 봉투 평균 가격

`trash_bag` 데이터는 지역별 종량제 봉투 가격 정보이다.  
각 용량별 가격 컬럼은 해당 행의 조건을 만족하는 봉투가 존재하면 가격을,  
존재하지 않으면 0을 값으로 갖는다.

용도가 **'음식물쓰레기'**이고 사용 대상이 **'가정용'**인 2L 봉투 가격의  
**평균**을 구하시오. (소수점 이하는 **절사**하여 **정수**로 출력)

**데이터**: `trash_bag.csv`
```
https://raw.githubusercontent.com/YoungjinBD/dataset/main/trash_bag.csv
```

> 출력: 평균 가격(정수, 절사)

In [3]:

df1 = pd.read_csv(
    "https://raw.githubusercontent.com/YoungjinBD/dataset/main/trash_bag.csv",
    encoding="cp949",
)
df1.head()

a = df1[(df1["용도"] == "음식물쓰레기") & (df1["사용대상"] == "가정용")]
result = a["2L가격"].mean().astype(int)

print(result)

61

## 문제 ② BMI 정상·과체중 인원 수 차이

BMI(Body Mass Index)는 몸무게(kg)를 키(m)의 제곱으로 나누어 계산하며,  
비만도를 나타내는 지표이다. 아래 기준에 따라 분류한다.

| BMI 범위 | 분류 |
|---|---|
| 18.5 미만 | 저체중 |
| 18.5 이상 ~ 23 미만 | 정상 |
| 23 이상 ~ 25 미만 | 과체중 |
| 25 이상 ~ 30 미만 | 경도비만 |
| 30 이상 | 중등도비만 |

제공된 BMI 데이터를 기준으로 **정상** 체중 인원과 **과체중** 인원의  
차이를 정수로 출력하시오.

**데이터**: `BMI.csv`
```
https://raw.githubusercontent.com/YoungjinBD/dataset/main/BMI.csv
```

> 출력: (정상 인원 수) − (과체중 인원 수) (정수)

In [4]:


df2 = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/BMI.csv")
df2.head()

   Gender  Height  Weight
0    Male     174      96
1    Male     189      87
2  Female     185     110
3  Female     195     104
4    Male     149      61

In [5]:
df2["bmi"] = df2["Weight"] / df2["Height"]**2 * 10000
# df2.head()
a = df2[(df2["bmi"] >= 18.5) & (df2["bmi"] < 23)].shape
b = df2[(df2["bmi"] >= 23) & (df2["bmi"] < 25)].shape
# result = a["bmi"].astype(int) - b["bmi"].astype(int)
47-19

28

## 문제 ③ 순전입학생 수가 가장 많은 학교

`students` 데이터는 학교별·학년별 **총 전입학생**, **총 전출학생**,  
**전체학생 수** 정보이다.

순전입학생 수는 다음과 같이 정의한다.

$$\text{순전입학생 수} = \text{총 전입학생} - \text{총 전출학생}$$

**순전입학생 수가 가장 많은 학교**의 **전체학생 수**를 구하시오.

**데이터**: `students.csv`
```
https://raw.githubusercontent.com/YoungjinBD/dataset/main/students.csv
```

> 출력: 해당 학교의 전체학생 수

In [6]:


df3 = pd.read_csv(
    "https://raw.githubusercontent.com/YoungjinBD/dataset/main/students.csv",
    encoding="cp949",
)
df3.head()

  학교  학년  총 전입학생  총 전출학생  전체학생 수
0  A   1       9       1     222
1  A   2      13       4     148
2  A   3       8       7     196
3  B   1       7       5     171
4  B   2       9       1     216

In [7]:
df3["순전입학생수"] = df3["총 전입학생"] - df3["총 전출학생"]
df3.head()

  학교  학년  총 전입학생  총 전출학생  전체학생 수  순전입학생수
0  A   1       9       1     222       8
1  A   2      13       4     148       9
2  A   3       8       7     196       1
3  B   1       7       5     171       2
4  B   2       9       1     216       8

In [15]:
df3 = df3.sort_values("순전입학생수", ascending=False)
df3.head()

   학교  학년  총 전입학생  총 전출학생  전체학생 수  순전입학생수
1   A   2      13       4     148       9
12  E   1      12       3     238       9
4   B   2       9       1     216       8
0   A   1       9       1     222       8
11  D   3       7       1     183       6

In [9]:
result2 = df3.groupby("학교")["순전입학생수"].sum()
result2

학교
A    18
B    13
C    -9
D     7
E    14
F     1
G    10
H    -1
Name: 순전입학생수, dtype: int64

In [13]:
result4 = df3[df3["학교"] == "A"]
sum_stu = result4["전체학생 수"].sum()
print(sum_stu)

566